UI: Fonts
threshold-network/bitcoin-on-base pull request #30
Opened 2024-01-24 15:36 UTC by kpyszkowski

Ref: #2 

This pull request replaces fonts packages to follow designs guidelines.
Currently used fonts are [DM Sans](https://fonts.google.com/specimen/DM+Sans) and [Bricolage Grotesque](https://fonts.google.com/specimen/Bricolage+Grotesque).

Initially font faces presented in Figma designs are [Aeonik Pro](https://aeonik.co.uk/font/) and [Neue Machina](https://pangrampangram.com/products/neue-machina). Those have been (temporarily) replaced by free-licensed alternatives.

Note: I've made a typo in commit messages - the font property that uses the _Bricolage Grotesque_ family is called `token-amount`, not `token-balance`.

Additional changes:
- Removed `chain-identifier` font style property. Removed uses of the property since it became deprecated.

2024-02-08 23:06 UTC, michalsmiarowski requested changes
Looking good to me! Let's resolve the conflicts with main branch first, before we merge and I will test it out again.

2024-02-13 13:24 UTC, kpyszkowski reviewed
The `main` branch has been merged. Works okay. Please confirm and merge 🔥

2024-02-14 12:45 UTC, michalsmiarowski requested changes

2024-02-14 13:05 UTC, kpyszkowski commented on package.json
> +    "@keep-network/tbtc": "development",
Ref commit: [306b7c3](https://github.com/threshold-network/bitcoin-on-base/pull/30/commits/306b7c3322fa782bb76893a6ff23f1ff38ee61e8)

2024-02-14 13:12 UTC, michalsmiarowski approved these changes
LGTM

2024-02-14 13:12 UTC, merged